global:
  scrape_interval: 3m
  evaluation_interval: 3m
 
scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['172.19.0.5:8089']
  - job_name: 'jenkins'
    metrics_path: '/prometheus/'
    scheme: http
    static_configs:
      - targets: ['172.17.0.1:8080']
    tls_config:
      insecure_skip_verify: true
      # - targets: ['172.17.0.1:8080']